# Workflow simples para fazer deploy de conteúdo estático no GitHub Pages
name: Deploy static content to Pages

on:
  # Executa em pushs na branch principal
  push:
    branches: ["main"]

  # Permite executar este workflow manualmente na aba Actions
  workflow_dispatch:

# Define permissões do GITHUB_TOKEN para permitir deployment no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deployment simultâneo, ignorando execuções em fila entre a execução em progresso e a última na fila.
# No entanto, NÃO cancela execuções em progresso para permitir que esses deployments de produção sejam completados.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job único para realizar o deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Clear GitHub Actions cache
        run: rm -rf ~/.npm ~/.cache ~/.yarn
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2